apiVersion: v1
kind: Secret
metadata:
  name: secret-video-studio
type: Opaque
stringData:
  APPLICATION_VERSION: latest
  SPRING_DATASOURCE_URL: jdbc:mysql://svc-db-video-studio:3306/videodb
  SPRING_DATASOURCE_USERNAME: videodbpass
  SPRING_DATASOURCE_PASSWORD: videodbpass
