apiVersion: v1
kind: Service
metadata:
  name: svc-video-studio
spec:
  type: NodePort
  # type: LoadBalancer // Quando for na AWS
  selector:
    app: deployment-video-studio
  ports:
    - port: 8080
      nodePort: 30001