apiVersion: v1
kind: Secret
metadata:
  name: secret-video-studio
type: Opaque
stringData:
  APPLICATION_VERSION: latest
  APPLICATION_DATABASE_VERSION: latest
  MYSQL_ROOT_PASSWORD: videodbpass
  MYSQL_DATABASE: videodb
  MYSQL_USER: videodbpass
  MYSQL_PASSWORD: videodbpass
  SPRING_DATASOURCE_USERNAME: videodbpass
  SPRING_DATASOURCE_PASSWORD: videodbpass