name: Security Check

on:
  workflow_dispatch:
  push:
  # workflow_run:
  #   workflows: ["Tests"]
  #   types:
  #     - completed

jobs:
  dependency-check:
    name: Dependency Check
    runs-on: ubuntu-latest
    concurrency:
      group: pull-request-preview-${{ github.event.workflow_run.head_repository.full_name }}-${{ github.event.workflow_run.head_branch }}
      cancel-in-progress: true

    permissions: write-all

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run OWASP Dependency-Check
        run: sh ./config/setup-security.sh ${{ secrets.OWASP_FAIL_BUILD_ON_CVSS_LEVEL }}

      # NÃO FUNCIONOU :(
      # - name: Set up Node.js
      #   uses: actions/setup-node@v4
      #   with:
      #     node-version: 18
      
      # - name: Update PR Status
      #   uses: actions/github-script@v7
      #   if: always()
      #   with:
      #     script: |
      #         const status = '${{ job.status }}';
      #         github.rest.repos.createCommitStatus({
      #           owner: context.repo.owner,
      #           repo: context.repo.repo,
      #           sha: context.sha,
      #           context: 'Dependency Check',
      #           description: 'Changed to status: ${{ job.status }}',
      #           state: status,
      #           target_url: 'https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}'
      #         })
            