name: Security Check

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["Unit Tests"]
    types:
      - completed

jobs:
  dependency-check:
    name: Dependency Check
    runs-on: ubuntu-latest
    permissions: write-all

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # - name: Run OWASP Dependency-Check
      #   run: sh ./config/setup-security.sh ${{ secrets.OWASP_FAIL_BUILD_ON_CVSS_LEVEL }}

      - name: Update PR Status to Success
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            await github.rest.repos.createCommitStatus({
              owner: context.repo.owner,
              repo: context.repo.repo,
              sha: context.sha,
              state: 'success',
              context: 'Dependency Check',
              description: 'Success',
              target_url: `https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}`
            });
