name: Security Check

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["Unit Tests"]
    types:
      - completed

jobs:
  dependency-check:
    runs-on: ubuntu-latest
    permissions: write-all

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run OWASP Dependency-Check
        run: sh ./config/setup-security.sh ${{ secrets.OWASP_FAIL_BUILD_ON_CVSS_LEVEL }}

      # A trick to avoid the the flow to be stuck
      - name: Confirm Completion
        run: echo "Security check completed successfully"
