name: Security Check

on:
  push:
  workflow_dispatch:

jobs:
  dependency-check:
    runs-on: ubuntu-latest
    permissions: write-all

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

#      - name: Set up Java JDK
#        uses: actions/setup-java@v4
#        with:
#          distribution: "temurin"
#          java-version: "17"
#          cache: "maven"
      #
      #      - name: Cache OWASP Dependency-Check data
      #        uses: actions/cache@v3
      #        with:
      #          path: ~/.m2/repository/org/owasp/dependency-check-data
      #          key: ${{ runner.os }}-dependency-check-${{ hashFiles('**/pom.xml') }}
      #          restore-keys: |
      #            ${{ runner.os }}-dependency-check-
      #
      #      - name: Run OWASP Dependency-Check
      #        run: |
      #          mvn dependency-check:check -DnvdApiKey=${{ secrets.OWASP_NVD_API_KEY }} -DfailBuildOnCVSS=${{ secrets.OWASP_FAIL_BUILD_ON_CVSS_LEVEL }}

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Run OWASP Dependency-Check
        run: |
          docker run --rm \
            -v $(pwd):/src \
            -e NVD_API_KEY=${{ secrets.OWASP_NVD_API_KEY }} \
            izhar0407/dependency-check \
            --project "video-studio" \
            --scan /src \
            --format "ALL" \
            --out /src/target/dependency-check-report \
            --failOnCVSS ${{ secrets.OWASP_FAIL_BUILD_ON_CVSS_LEVEL }}
